class BannerAutogenerated {
  int code;
  String msg;
  List<BannerModel> data;

  BannerAutogenerated({this.code, this.msg, this.data});

  BannerAutogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    msg = json['msg'];
    if (json['data'] != null) {
      data = new List<BannerModel>();
      json['data'].forEach((v) {
        data.add(new BannerModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    data['msg'] = this.msg;
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class BannerModel {
  String id;
  int createTime;
  String bannerUrl;
  String bannerPage;
  Null param;
  String title;
  String type;
  String url;
  int isShow;

  BannerModel(
      {this.id,
      this.createTime,
      this.bannerUrl,
      this.bannerPage,
      this.param,
      this.title,
      this.type,
      this.url,
      this.isShow});

  BannerModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    createTime = json['createTime'];
    bannerUrl = json['bannerUrl'];
    bannerPage = json['bannerPage'];
    param = json['param'];
    title = json['title'];
    type = json['type'];
    url = json['url'];
    isShow = json['isShow'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['createTime'] = this.createTime;
    data['bannerUrl'] = this.bannerUrl;
    data['bannerPage'] = this.bannerPage;
    data['param'] = this.param;
    data['title'] = this.title;
    data['type'] = this.type;
    data['url'] = this.url;
    data['isShow'] = this.isShow;
    return data;
  }
}
